"""
Generic Dynamic DAG Factory for Apache Airflow.

Reads JSON/YAML files from ``configs/`` and generates Airflow DAG objects
while the DAG file is parsed.

Directory contract::

    /opt/airflow/dags/
    ├── dynamic_dag_factory.py
    └── configs/
        ├── customer_order.json

No static factory can infer arbitrary business logic. This implementation is
generic for operator-based DAGs. Custom Python logic must be provided as an
importable operator, callable or timetable and referenced by configuration.
"""

from __future__ import annotations

import importlib
import json
import logging
import os
import re
from datetime import timedelta
from pathlib import Path
from typing import Any, Iterable, Mapping

import pendulum
from airflow import DAG
from airflow.models.baseoperator import BaseOperator
from airflow.utils.dag_parsing_context import get_parsing_context
from airflow.utils.task_group import TaskGroup

LOGGER = logging.getLogger(__name__)

DEFAULT_CONFIG_DIR = Path(__file__).resolve().parent / "configs"
CONFIG_DIR = Path(
    os.getenv("AIRFLOW_DYNAMIC_DAG_CONFIG_DIR", str(DEFAULT_CONFIG_DIR))
)

# By default, one invalid config is isolated instead of removing every valid
# DAG generated by this single factory file.
FAIL_FAST = os.getenv("AIRFLOW_FACTORY_FAIL_FAST", "false").lower() in {
    "1",
    "true",
    "yes",
}

# User-supplied Python import paths are intentionally restricted.
ALLOW_ARBITRARY_IMPORTS = os.getenv(
    "AIRFLOW_FACTORY_ALLOW_ARBITRARY_IMPORTS",
    "false",
).lower() in {"1", "true", "yes"}

ALLOWED_IMPORT_PREFIXES = tuple(
    prefix.strip()
    for prefix in os.getenv(
        "AIRFLOW_FACTORY_ALLOWED_IMPORT_PREFIXES",
        "platform_tasks.,platform_operators.,platform_callbacks.,platform_timetables.",
    ).split(",")
    if prefix.strip()
)

ID_PATTERN = re.compile(r"^[A-Za-z0-9_.-]+$")

# Alias -> import path. Imports are lazy, so a provider is required only when
# a configuration actually uses that task type.
OPERATOR_ALIASES: dict[str, str] = {
    "empty": "airflow.operators.empty.EmptyOperator",
    "bash": "airflow.operators.bash.BashOperator",
    "python": "airflow.operators.python.PythonOperator",
    "branch_python": "airflow.operators.python.BranchPythonOperator",
    "short_circuit": "airflow.operators.python.ShortCircuitOperator",
    "spark": (
        "airflow.providers.apache.spark.operators.spark_submit."
        "SparkSubmitOperator"
    ),
    "sql": (
        "airflow.providers.common.sql.operators.sql."
        "SQLExecuteQueryOperator"
    ),
    "kubernetes_pod": (
        "airflow.providers.cncf.kubernetes.operators.pod."
        "KubernetesPodOperator"
    ),
    "http": "airflow.providers.http.operators.http.HttpOperator",
    "email": "airflow.operators.email.EmailOperator",
    "trigger_dag": "airflow.operators.trigger_dagrun.TriggerDagRunOperator",
    "file_sensor": "airflow.sensors.filesystem.FileSensor",
    "external_task_sensor": "airflow.sensors.external_task.ExternalTaskSensor",
    "time_delta_sensor": "airflow.sensors.time_delta.TimeDeltaSensor",
}

TIMEDELTA_FIELDS = {
    "retry_delay_seconds": "retry_delay",
    "execution_timeout_seconds": "execution_timeout",
    "sla_seconds": "sla",
    "execution_delta_seconds": "execution_delta",
}

COMMON_TASK_FIELDS = {
    "retries",
    "depends_on_past",
    "wait_for_downstream",
    "email",
    "email_on_failure",
    "email_on_retry",
    "pool",
    "pool_slots",
    "queue",
    "priority_weight",
    "weight_rule",
    "trigger_rule",
    "max_active_tis_per_dag",
    "max_active_tis_per_dagrun",
    "do_xcom_push",
    "executor_config",
}


class FactoryConfigError(ValueError):
    """Raised when a dynamic DAG configuration is invalid."""


def _as_bool(value: Any, default: bool = False) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().lower() in {"1", "true", "yes", "on"}
    return bool(value)


def _validate_id(value: Any, field_name: str, source: Path) -> str:
    if not isinstance(value, str) or not value:
        raise FactoryConfigError(
            f"{source}: {field_name} must be a non-empty string"
        )
    if not ID_PATTERN.fullmatch(value):
        raise FactoryConfigError(
            f"{source}: {field_name}={value!r} contains unsupported characters"
        )
    return value


def _to_timedelta(value: Any, field_name: str) -> timedelta:
    try:
        seconds = int(value)
    except (TypeError, ValueError) as exc:
        raise FactoryConfigError(
            f"{field_name} must be an integer number of seconds"
        ) from exc

    if seconds < 0:
        raise FactoryConfigError(f"{field_name} must be >= 0")

    return timedelta(seconds=seconds)


def _parse_datetime(
    value: str | None,
    timezone_name: str,
    field_name: str,
) -> pendulum.DateTime | None:
    if value is None:
        return None
    if not isinstance(value, str):
        raise FactoryConfigError(f"{field_name} must be a string")

    parsed = pendulum.parse(value, strict=False)
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=pendulum.timezone(timezone_name))
    return parsed


def _load_symbol(import_path: str, *, trusted_builtin: bool = False) -> Any:
    """Load ``package.module.Symbol`` using an import allow-list."""
    if not isinstance(import_path, str) or "." not in import_path:
        raise FactoryConfigError(f"Invalid import path: {import_path!r}")

    if not trusted_builtin and not ALLOW_ARBITRARY_IMPORTS:
        if not any(
            import_path.startswith(prefix)
            for prefix in ALLOWED_IMPORT_PREFIXES
        ):
            raise FactoryConfigError(
                f"Import path {import_path!r} is not allowed. Add its package "
                "prefix to AIRFLOW_FACTORY_ALLOWED_IMPORT_PREFIXES."
            )

    module_name, symbol_name = import_path.rsplit(".", 1)
    module = importlib.import_module(module_name)

    try:
        return getattr(module, symbol_name)
    except AttributeError as exc:
        raise FactoryConfigError(
            f"Symbol {symbol_name!r} does not exist in {module_name!r}"
        ) from exc


def _resolve_callable(value: Any) -> Any:
    """Resolve ``package.module.function`` or ``package.module:function``."""
    if callable(value):
        return value
    if not isinstance(value, str):
        return value
    return _load_symbol(value.replace(":", "."))


def _read_config_file(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as file:
        if path.suffix.lower() == ".json":
            data = json.load(file)
        elif path.suffix.lower() in {".yaml", ".yml"}:
            try:
                import yaml
            except ImportError as exc:
                raise FactoryConfigError(
                    "PyYAML is required to read YAML configuration files"
                ) from exc
            data = yaml.safe_load(file)
        else:
            raise FactoryConfigError(
                f"Unsupported config extension: {path.suffix}"
            )

    if not isinstance(data, dict):
        raise FactoryConfigError(
            f"{path}: document root must be an object/mapping"
        )
    return data


def _iter_config_files() -> list[Path]:
    if not CONFIG_DIR.exists():
        LOGGER.warning(
            "Dynamic DAG config directory does not exist: %s",
            CONFIG_DIR,
        )
        return []

    return sorted(
        [
            *CONFIG_DIR.glob("*.json"),
            *CONFIG_DIR.glob("*.yaml"),
            *CONFIG_DIR.glob("*.yml"),
        ],
        key=lambda path: path.name,
    )


def _build_default_args(config: Mapping[str, Any]) -> dict[str, Any]:
    result = dict(config.get("default_args") or {})

    # Existing schema compatibility: retry_delay is interpreted as seconds
    # when it is not already a timedelta object.
    if "retry_delay_seconds" in result:
        result["retry_delay"] = _to_timedelta(
            result.pop("retry_delay_seconds"),
            "default_args.retry_delay_seconds",
        )
    elif "retry_delay" in result and not isinstance(
        result["retry_delay"], timedelta
    ):
        result["retry_delay"] = _to_timedelta(
            result["retry_delay"],
            "default_args.retry_delay",
        )

    for source_field, target_field in (
        ("execution_timeout_seconds", "execution_timeout"),
        ("sla_seconds", "sla"),
    ):
        if source_field in result:
            result[target_field] = _to_timedelta(
                result.pop(source_field),
                f"default_args.{source_field}",
            )

    for callback_name in (
        "on_failure_callback",
        "on_success_callback",
        "on_retry_callback",
        "on_execute_callback",
        "sla_miss_callback",
    ):
        if isinstance(result.get(callback_name), str):
            result[callback_name] = _resolve_callable(result[callback_name])

    if "retries" in result:
        result["retries"] = int(result["retries"])

    return result


def _build_schedule(raw_schedule: Any) -> Any:
    """
    Accept cron/preset/null or a custom timetable object.

    Example::

        "schedule": {
          "class_path": "platform_timetables.BusinessTimetable",
          "kwargs": {}
        }
    """
    if not isinstance(raw_schedule, dict):
        return raw_schedule

    class_path = raw_schedule.get("class_path")
    if not class_path:
        raise FactoryConfigError("A schedule object requires class_path")

    timetable_class = _load_symbol(class_path)
    return timetable_class(**dict(raw_schedule.get("kwargs") or {}))


def _build_dag(config: dict[str, Any], source: Path) -> DAG:
    dag_id = _validate_id(config.get("dag_id"), "dag_id", source)
    timezone_name = config.get("timezone", "Asia/Bangkok")

    dag_kwargs: dict[str, Any] = {
        "dag_id": dag_id,
        "description": config.get("description"),
        "schedule": _build_schedule(config.get("schedule")),
        "start_date": _parse_datetime(
            config.get("start_date"), timezone_name, "start_date"
        ),
        "end_date": _parse_datetime(
            config.get("end_date"), timezone_name, "end_date"
        ),
        "catchup": _as_bool(config.get("catchup"), False),
        "default_args": _build_default_args(config),
        "tags": config.get("tags") or [],
        "params": config.get("params") or {},
        "max_active_runs": int(config.get("max_active_runs", 1)),
        "max_active_tasks": int(config.get("max_active_tasks", 16)),
        "render_template_as_native_obj": _as_bool(
            config.get("render_template_as_native_obj"), False
        ),
    }

    for field in (
        "template_searchpath",
        "doc_md",
        "access_control",
        "is_paused_upon_creation",
        "orientation",
        "default_view",
    ):
        if field in config:
            dag_kwargs[field] = config[field]

    if config.get("dagrun_timeout_seconds") is not None:
        dag_kwargs["dagrun_timeout"] = _to_timedelta(
            config["dagrun_timeout_seconds"],
            "dagrun_timeout_seconds",
        )

    for callback_name in (
        "on_failure_callback",
        "on_success_callback",
        "sla_miss_callback",
    ):
        if config.get(callback_name):
            dag_kwargs[callback_name] = _resolve_callable(
                config[callback_name]
            )

    return DAG(**dag_kwargs)


def _build_task_groups(
    config: Mapping[str, Any],
    dag: DAG,
    source: Path,
) -> dict[str, TaskGroup]:
    groups: dict[str, TaskGroup] = {}
    pending = sorted(
        config.get("task_groups") or [],
        key=lambda item: item.get("group_id", ""),
    )

    while pending:
        progress = False

        for group_config in list(pending):
            group_id = _validate_id(
                group_config.get("group_id"),
                "task_groups.group_id",
                source,
            )
            parent_id = group_config.get("parent_group_id")

            if parent_id and parent_id not in groups:
                continue

            kwargs: dict[str, Any] = {
                "group_id": group_id,
                "dag": dag,
                "tooltip": group_config.get("tooltip"),
                "prefix_group_id": _as_bool(
                    group_config.get("prefix_group_id"), True
                ),
                "add_suffix_on_collision": _as_bool(
                    group_config.get("add_suffix_on_collision"), False
                ),
            }
            if parent_id:
                kwargs["parent_group"] = groups[parent_id]

            groups[group_id] = TaskGroup(**kwargs)
            pending.remove(group_config)
            progress = True

        if not progress:
            unresolved = [item.get("group_id") for item in pending]
            raise FactoryConfigError(
                f"{source}: unresolved or cyclic TaskGroup parents: "
                f"{unresolved}"
            )

    return groups


def _build_common_task_args(
    task_config: Mapping[str, Any],
) -> dict[str, Any]:
    result = dict(task_config.get("task_args") or {})

    for field in COMMON_TASK_FIELDS:
        if field in task_config and field not in result:
            result[field] = task_config[field]

    for source_field, target_field in TIMEDELTA_FIELDS.items():
        value = None
        if source_field in result:
            value = result.pop(source_field)
        elif source_field in task_config:
            value = task_config[source_field]

        if value is not None:
            result[target_field] = _to_timedelta(value, source_field)

    if "retry_delay" in result and not isinstance(
        result["retry_delay"], timedelta
    ):
        result["retry_delay"] = _to_timedelta(
            result["retry_delay"], "task.retry_delay"
        )

    for callback_name in (
        "on_failure_callback",
        "on_success_callback",
        "on_retry_callback",
        "on_execute_callback",
    ):
        if isinstance(result.get(callback_name), str):
            result[callback_name] = _resolve_callable(result[callback_name])

    if "retries" in result:
        result["retries"] = int(result["retries"])

    return result


def _get_operator_class(
    task_config: Mapping[str, Any],
) -> type[BaseOperator]:
    operator_path = task_config.get("operator")

    if operator_path:
        operator_class = _load_symbol(operator_path)
    else:
        task_type = task_config.get("task_type")
        if task_type not in OPERATOR_ALIASES:
            raise FactoryConfigError(
                f"Unsupported task_type={task_type!r}. Known aliases: "
                f"{sorted(OPERATOR_ALIASES)}. Use 'operator' for an "
                "approved custom BaseOperator class."
            )
        operator_class = _load_symbol(
            OPERATOR_ALIASES[task_type],
            trusted_builtin=True,
        )

    if not isinstance(operator_class, type) or not issubclass(
        operator_class, BaseOperator
    ):
        raise FactoryConfigError(
            f"{operator_class!r} is not an Airflow BaseOperator class"
        )

    return operator_class


def _normalize_operator_args(
    task_config: Mapping[str, Any],
) -> dict[str, Any]:
    # operator_args is the generic name. task_params remains supported for
    # compatibility with existing JSON files.
    operator_args = dict(
        task_config.get("operator_args")
        or task_config.get("task_params")
        or {}
    )

    task_type = task_config.get("task_type")
    conn_id = task_config.get("conn_id")

    if conn_id:
        connection_arg_by_type = {
            "spark": "conn_id",
            "sql": "conn_id",
            "http": "http_conn_id",
            "kubernetes_pod": "kubernetes_conn_id",
            "file_sensor": "fs_conn_id",
        }
        connection_arg = connection_arg_by_type.get(task_type)
        if connection_arg and connection_arg not in operator_args:
            operator_args[connection_arg] = conn_id

    for callable_field in (
        "python_callable",
        "on_failure_callback",
        "on_success_callback",
        "on_retry_callback",
        "on_execute_callback",
        "response_check",
        "response_filter",
    ):
        if isinstance(operator_args.get(callable_field), str):
            operator_args[callable_field] = _resolve_callable(
                operator_args[callable_field]
            )

    for source_field, target_field in TIMEDELTA_FIELDS.items():
        if source_field in operator_args:
            operator_args[target_field] = _to_timedelta(
                operator_args.pop(source_field),
                f"operator_args.{source_field}",
            )

    return operator_args


def _build_task(
    task_config: dict[str, Any],
    dag: DAG,
    task_groups: Mapping[str, TaskGroup],
    source: Path,
) -> BaseOperator:
    task_id = _validate_id(
        task_config.get("task_id"), "tasks.task_id", source
    )
    operator_class = _get_operator_class(task_config)
    operator_args = _normalize_operator_args(task_config)
    common_args = _build_common_task_args(task_config)

    group_id = task_config.get("group_id")
    task_group = None
    if group_id:
        try:
            task_group = task_groups[group_id]
        except KeyError as exc:
            raise FactoryConfigError(
                f"{source}: task {task_id!r} references missing "
                f"TaskGroup {group_id!r}"
            ) from exc

    return operator_class(
        task_id=task_id,
        dag=dag,
        task_group=task_group,
        **common_args,
        **operator_args,
    )


def _iter_dependency_edges(
    config: Mapping[str, Any],
) -> Iterable[tuple[str, str]]:
    for task_config in config.get("tasks") or []:
        current_id = task_config["task_id"]

        upstream_ids = (
            task_config.get("depends_on")
            or task_config.get("depend_on")
            or task_config.get("upstream_task_ids")
            or []
        )
        if isinstance(upstream_ids, str):
            upstream_ids = [upstream_ids]
        for upstream_id in upstream_ids:
            yield str(upstream_id), current_id

        downstream_ids = task_config.get("downstream_task_ids") or []
        if isinstance(downstream_ids, str):
            downstream_ids = [downstream_ids]
        for downstream_id in downstream_ids:
            yield current_id, str(downstream_id)

    for dependency in config.get("dependencies") or []:
        if isinstance(dependency, (list, tuple)) and len(dependency) == 2:
            yield str(dependency[0]), str(dependency[1])
            continue

        if not isinstance(dependency, dict):
            raise FactoryConfigError(
                "Each dependency must be an object or [upstream, downstream]"
            )

        upstream = dependency.get("upstream_task_id") or dependency.get(
            "upstream"
        )
        downstream = dependency.get("downstream_task_id") or dependency.get(
            "downstream"
        )
        if not upstream or not downstream:
            raise FactoryConfigError(f"Invalid dependency: {dependency!r}")
        yield str(upstream), str(downstream)


def _validate_acyclic(
    task_ids: set[str],
    edges: list[tuple[str, str]],
    source: Path,
) -> None:
    adjacency = {task_id: [] for task_id in task_ids}
    indegree = {task_id: 0 for task_id in task_ids}

    for upstream, downstream in edges:
        if upstream not in task_ids:
            raise FactoryConfigError(
                f"{source}: missing upstream task {upstream!r}"
            )
        if downstream not in task_ids:
            raise FactoryConfigError(
                f"{source}: missing downstream task {downstream!r}"
            )
        if upstream == downstream:
            raise FactoryConfigError(
                f"{source}: task {upstream!r} cannot depend on itself"
            )
        adjacency[upstream].append(downstream)
        indegree[downstream] += 1

    queue = sorted(
        task_id for task_id, degree in indegree.items() if degree == 0
    )
    visited = 0

    while queue:
        current = queue.pop(0)
        visited += 1
        for downstream in sorted(adjacency[current]):
            indegree[downstream] -= 1
            if indegree[downstream] == 0:
                queue.append(downstream)
                queue.sort()

    if visited != len(task_ids):
        raise FactoryConfigError(
            f"{source}: task dependencies contain a cycle"
        )


def create_dag(config: dict[str, Any], source: Path) -> DAG:
    """Create one DAG object, all tasks and all dependencies."""
    tasks_config = config.get("tasks")
    if not isinstance(tasks_config, list) or not tasks_config:
        raise FactoryConfigError(
            f"{source}: 'tasks' must be a non-empty list"
        )

    dag = _build_dag(config, source)
    task_groups = _build_task_groups(config, dag, source)
    task_objects: dict[str, BaseOperator] = {}

    # Pass 1: create every task first, independent of JSON/YAML ordering.
    for task_config in sorted(
        tasks_config,
        key=lambda item: item.get("task_id", ""),
    ):
        task = _build_task(task_config, dag, task_groups, source)
        if task.task_id in task_objects:
            raise FactoryConfigError(
                f"{source}: duplicate task_id={task.task_id!r}"
            )
        task_objects[task.task_id] = task

    # Pass 2: validate and connect dependencies.
    unique_edges = sorted(set(_iter_dependency_edges(config)))
    _validate_acyclic(set(task_objects), unique_edges, source)

    for upstream_id, downstream_id in unique_edges:
        task_objects[upstream_id] >> task_objects[downstream_id]

    return dag

# Airflow module-level registration
PARSING_DAG_ID = get_parsing_context().dag_id
LOAD_ERRORS: list[str] = []
GENERATED_DAG_IDS: set[str] = set()

for config_path in _iter_config_files():
    try:
        config = _read_config_file(config_path)

        enabled = config.get("enabled", config.get("active", True))
        if not _as_bool(enabled, True):
            LOGGER.info("Skipping disabled DAG config: %s", config_path)
            continue

        dag_id = _validate_id(config.get("dag_id"), "dag_id", config_path)

        # Official Airflow parsing-context optimization: during task
        # execution, generate only the requested DAG instead of every DAG.
        if PARSING_DAG_ID is not None and PARSING_DAG_ID != dag_id:
            continue

        if dag_id in GENERATED_DAG_IDS:
            raise FactoryConfigError(
                f"Duplicate dag_id={dag_id!r} across config files"
            )

        generated_dag = create_dag(config, config_path)
        GENERATED_DAG_IDS.add(dag_id)

        # Explicit module-level registration.
        globals()[dag_id] = generated_dag

        LOGGER.info("Generated DAG %s from %s", dag_id, config_path)

    except Exception as exc:
        message = f"Failed to generate DAG from {config_path}: {exc}"
        LOAD_ERRORS.append(message)
        LOGGER.exception(message)

        if FAIL_FAST:
            raise

# If every file failed, expose an Airflow import error rather than leaving the
# UI empty with only scheduler log messages.
if LOAD_ERRORS and not GENERATED_DAG_IDS:
    raise FactoryConfigError(
        "No dynamic DAG could be generated:\n- " + "\n- ".join(LOAD_ERRORS)
    )
